### ISSUE TITLE
Reference to 'hash' is ambiguous

### ISSUE THREAD

**Issue by amin-saffari** [champost/ABLE#15]
Hi Champak,

I am trying to compile ABLE with gcc 6.2.1 20160830 . It seems the function "hash" at [utils.h](https://github.com/champost/ABLE/blob/master/utils.h#L69) creats ambiguity to the compiler. The compiler wants to use std::hash in [gsl_rng_set](https://github.com/champost/ABLE/blob/master/main.cpp#L1187) instead of your hash.

Cheers,
Amin

**Comment by champost** [comment]
Hi @amin-saffari, I think the ambiguity arises due to the existence of a "new" (_i.e._ C++11 standard) [`hash`](http://www.cplusplus.com/reference/functional/hash/) function in the C++ STL. This should be easy to fix and you could already try to rename the function as `hashABLE` (for example) in [utils.h](https://github.com/champost/ABLE/blob/master/utils.h#L69) and also in main.cpp on [L1187](https://github.com/champost/ABLE/blob/master/main.cpp#L1187) and [L1238](https://github.com/champost/ABLE/blob/master/main.cpp#L1238).

**Comment by amin-saffari** [comment]
Hi @champost,

I fixed the ambiguity by creating a new namespace and put hash in it. However it would have been awesome if we (userABLE) have either of the solutions at master branch! 

Cheers,
Amin

**Comment by champost** [comment]
Ok, this will show up in my next push to remote.
